### PR TITLE
Replace youtube-dl with yt-dlp

### PR DESCRIPTION
**Pull request by krisdoodle45**
Relevant issue (on voidrice repo) https://github.com/LukeSmithxyz/voidrice/issues/1018

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
(I'm not against rebirthing pip installation in this script if needbe. The pip install of the package works fine now, but I would prefer the AUR build if possible.)

**Comment by narukeh** [comment]
@LukeSmithxyz `yt-dlp` is now in the main repos btw.
also no need to choose either one when you can have both, they do not conflict with each other. but mpv still expects a `youtube-dl` binary in path, sooo:
`cat /usr/local/bin/youtube-dl`
```bash
#!/bin/sh

#test -f /usr/bin/youtube-dl && yt='/usr/bin/youtube-dl'
test -f /usr/bin/yt-dlp && yt='/usr/bin/yt-dlp'

exec "$yt" "$@"
```
(when you look at $PATH, /usr/local/bin has precedence over /usr/bin)

**Comment by LukeSmithxyz** [comment]
There is still no reason to switch to add yt-dlp because it has not even resolved the issue allegedly wrong with youtube-dl.

**Comment by RaZ0rr-Two** [comment]
The youtube-dl subreddit recommends switching to yt-dlp because many of the users have reported to solving the throttling issue (slow downloads) after switching. More info from the pinned comment on their sub, 
[READ: SLOW YOUTUBE DOWNLOADS](https://www.reddit.com/r/youtubedl/comments/qfbyal/read_slow_youtube_downloads/)

**Pull request closed without merging**
