### PR TITLE
brave -> brave-bin

### PR DESCRIPTION
**Pull request by yukki-14**

### CODE REVIEW

**Review by Dark-Matter7232 — COMMENTED** [review]
But why?

**Comment by kronikpillow** [comment]
luke please accept this pull requiest, the brave package takes a hell of a long time to install, plus who ever placed the brave package instead of the brave-bin package, removed the A, flag and brave and gnu-free-fonts do not install because of it as it's searching the Arch repos instead of the AUR

**Comment by osmanky** [comment]
Had the same issue today. Fresh install followed by LARBS execution does not install brave and gnu-free-fonts. Had to install them manually.

**Comment by jemadux** [comment]
does brave-bin display brave-ads on larbs ? 
i am kinda worry ... 
and plus brave dont have history ...

**Comment by kronikpillow** [comment]
> does brave-bin display brave-ads on larbs ? i am kinda worry ... and plus brave dont have history ...

what are you even talking about? since when does brave not have history? O.o

**Pull request merged**
