### PR TITLE
Fix github-based progs typo

### PR DESCRIPTION
**Pull request by ZethJack**
Some github-based programs don't get installed because of the typo in the username (it's case sensitive) This resulted in installed system missing some crucial parts such as st, dmenu, dwm.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Under what cases is it case sensitive? I can clone them all now regardless of capitalization.

**Comment by ZethJack** [comment]
When trying to clone the repository with git, it returns error:
remote: Repository not found.
fatal: repository 'https://github.com/lukesmith.xyz/dwm.git/' not found

So yes, it does seem like it is case sensitive. Of course larbs.sh
doesn't show you this error so you have no way of knowing.

**Comment by WhispersOfJ** [comment]
That's because the link is actually https://github.com/LukeSmithxyz/dwm.git

**Comment by LukeSmithxyz** [comment]
Any capitalization scheme of the username correctly spelled (even capitalizing random letters) will clone it successfully.

**Pull request closed without merging**
